### ISSUE TITLE
API: return of user list doesn't contain objectId for enrollments

### ISSUE THREAD

**Issue by tlan16** [nathansherburn/kusema#42]
Please check if the same issue exist for subscriptions

**Comment by akdor1154** [comment]
as per hangouts convo, we are providing the _id of groups and topics, this _id is just a String, not an ObjectId. Is this all OK?
Note that I'm locked out of the melts-dev machine until I go in to Monash as they've locked out external ssh access. :( As such I can't update it to the latest version right away.
If you want to use the latest version of the code in the meantime, git pull Nathan's version and run npm install, the bin/kusema test.

I have also manually amended all User objects on melts-dev to conform to the new schema.
Note that schemas actually have nothing to do with MongoDB, they are just enforced by the second layer, Mongoose. As such if we do ever modify anything, old data will still persist in the database. It's thus important not to rely on anything you see that is not given in the schema document. If there's anything more you need that's not specified in the document, let me know and I'll mark it unchangeable and add it to the doc.

Jarrad

**Comment by tlan16** [comment]
I didn't realise you can customise the id. I thought it's handled by mango automatic. 

Anyway, I have done the topic and group connector and importer yesterday. Everything is fine. 

Kind Regards
Frank Lan
Budget PC Pty Ltd

**Comment by akdor1154** [comment]
sweet, yeah it was a little cheeky of me but seems to be a valid misuse of Mongo :)
