### ISSUE TITLE
API error

### ISSUE THREAD

**Issue by tlan16** [nathansherburn/kusema#45]
for this url
http://melts-dev.eng.monash.edu:8003/rest/questions?populate={%22path%22:%22group%22}
internal server error will occur

{"status":500,"name":"Internal Server Error","message":"Cast to ObjectId failed for value \"eng1003\" at path \"_id\" (500).","stack":"Error\n    at MongooseError.CastError (/srv/home/jmwhi13/kusema/Server/node_modules/mongoose/lib/error/cast.js:18:16)\n    at ObjectId.cast (/srv/home/jmwhi13/kusema/Server/node_modules/mongoose/lib/schema/objectid.js:134:13)\n    at /srv/home/jmwhi13/kusema/Server/node_modules/mongoose/lib/schema/objectid.js:155:17\n    at Array.map (native)\n    at ObjectId.handleArray (/srv/home/jmwhi13/kusema/Server/node_modules/mongoose/lib/schema/objectid.js:154:14)\n    at ObjectId.castForQuery (/srv/home/jmwhi13/kusema/Server/node_modules/mongoose/lib/schema/objectid.js:185:20)\n    at module.exports (/srv/home/jmwhi13/kusema/Server/node_modules/mongoose/lib/cast.js:196:39)\n    at Query.cast (/srv/home/jmwhi13/kusema/Server/node_modules/mongoose/lib/query.js:2487:10)\n    at Query.find (/srv/home/jmwhi13/kusema/Server/node_modules/mongoose/lib/query.js:1087:10)\n    at Function.find (/srv/home/jmwhi13/kusema/Server/node_modules/mongoose/lib/model.js:1054:13)\n    at populate (/srv/home/jmwhi13/kusema/Server/node_modules/mongoose/lib/model.js:2367:15)\n    at Function.Model.populate (/srv/home/jmwhi13/kusema/Server/node_modules/mongoose/lib/model.js:2204:5)\n    at QueryStream._onNextObject (/srv/home/jmwhi13/kusema/Server/node_modules/mongoose/lib/querystream.js:232:20)\n    at cursorcb (/srv/home/jmwhi13/kusema/Server/node_modules/mongoose/lib/querystream.js:176:10)\n    at handleCallback (/srv/home/jmwhi13/kusema/Server/node_modules/mongoose/node_modules/mongodb/lib/utils.js:95:12)\n    at /srv/home/jmwhi13/kusema/Server/node_modules/mongoose/node_modules/mongodb/lib/cursor.js:597:5"}

**Comment by akdor1154** [comment]
Hey,
looks like a mongoose bug: https://github.com/Automattic/mongoose/issues/2535
For now, a workaround would be to not populate groups and topics -- just pull them directly at the start, store them in an associative array [topic->_id => topic], then look up the needed topic when you pull. This will save on bandwidth and server load anyway so it would probably be worth doing even if mongoose wasn't a buggy obtuse box of magic.
